version: 2

sources:
  - name: bike_production
    database: bike_stores
    schema: bike_production
    tables:
      - name: brands
      - name: categories
      - name: products
      - name: stocks
  - name: bike_sales
    database: bike_stores
    schema: bike_sales
    tables:
      - name: categories
      - name: customers
      - name: orders
      - name: order_items
      - name: staffs
      - name: stores
